apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-migration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/argocd-3tier-app.git
    targetRevision: main
    path: migration
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
